### ISSUE TITLE
Question: Documentation Missing

### ISSUE THREAD

**Issue by deccer** [Joshua-Ashton/Shadey#1]
Hi @Joshua-Ashton do you plan on adding some sort of documentation/README/wiki etc?

This project sounds like an interesting addon for the `Graphics Programming` discord.

Cheers

**Comment by misyltoad** [comment]
Maybe, there's not much to document other than you put a token in some header as a const value with a name and build.

**Comment by deccer** [comment]
That's given, but which header, what commands to use etc.
If you want people to use it, that is.

I am sorry if I have wasted your time.
